100 "TIMER"
110 "L": CLEAR : WAIT 59: PRINT "TIMER V.0.1"
120 INPUT "M-IN/S-EC?:";TTP$: INPUT "COUNT?:";TC
130 IF TTP$<>"S" AND TTP$<>"M" THEN LET TTP$="S"
140 IF TTP$="M" THEN LET TTT=3540: LET TTN$="MIN."
150 IF TTP$="S" THEN LET TTT=59: LET TTN$="SEC."
160 FOR TI=TC TO 1 STEP -1
170 WAIT TTT: PRINT "TIMER";"(";TTN$;"):";TI: NEXT TI
180 FOR TIM=1 TO 4: BEEP 2: PRINT ">>!TIME IS UP!<<": NEXT TIM
190 WAIT : PRINT ">>!TIME IS UP!<<": END 